package com.example.myapp;

import static com.codename1.ui.CN.*;

import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

import com.example.myapp.forms.*;
/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class LoginForm extends Form {
    public void showLoginForm() {
        Form form = new Form("Sign in", BoxLayout.y());
        Label usernameLabel = new Label();
        TextField username = new TextField();
        Label passwordLabel = new Label();
        TextField password = new TextField();
        Button login = new Button("Login");
        Button forgot = new Button("Forgot your password?");

        login.addActionListener(e -> {
            ProfileForm profile = new ProfileForm();
            profile.showProfileForm();
        });
        forgot.addActionListener(e -> {
            TokenForm token = new TokenForm();
            token.showGenerateForm();
        });

        form.add(usernameLabel);
        form.add(username);
        form.add(passwordLabel);
        form.add(password);
        form.add(login);
        form.add(forgot);

        form.show();
    }
}
