package com.example.myapp;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

import com.example.myapp.forms.*;
/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class ProfileForm extends Lifecycle {
    public void showProfileForm() {
        Form form = new Form("My profile", BoxLayout.y());
        TextField username = new TextField();
        TextField email = new TextField();
        Button logout = new Button("Logout");

        logout.addActionListener(e -> {
            LoginForm login = new LoginForm();
            login.showLoginForm();
        });

        username.setText("Example #1");
        email.setText("Example #2");

        form.add(username);
        form.add(email);
        form.add(logout);

        form.show();
    }
}
